/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    'event-genres': EventGenre;
    'menu-items': MenuItem;
    'calendar-subscribers': CalendarSubscriber;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-genres': EventGenresSelect<false> | EventGenresSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'calendar-subscribers': CalendarSubscribersSelect<false> | CalendarSubscribersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'business-info': BusinessInfo;
    'facebook-config': FacebookConfig;
    'system-config': SystemConfig;
  };
  globalsSelect: {
    'business-info': BusinessInfoSelect<false> | BusinessInfoSelect<true>;
    'facebook-config': FacebookConfigSelect<false> | FacebookConfigSelect<true>;
    'system-config': SystemConfigSelect<false> | SystemConfigSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texte alternatif pour l'accessibilité
   */
  alt?: string | null;
  /**
   * Légende de l'image (optionnel)
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Nom de l'événement
   */
  title: string;
  /**
   * Identifiant unique pour l'événement (utilisé dans l'URL)
   */
  slug: string;
  /**
   * Date de l'événement
   */
  date: string;
  /**
   * Heure de l'événement (ex: 20h00, 19h30)
   */
  time?: string | null;
  /**
   * Affiche officielle de l'événement (optionnel)
   */
  image?: (number | null) | Media;
  /**
   * Image de couverture Facebook (utilisée si pas d'affiche officielle)
   */
  facebookCover?: (number | null) | Media;
  /**
   * Lien vers l'événement Facebook (optionnel)
   */
  facebookLink?: string | null;
  /**
   * Genre de l'événement (automatiquement assigné selon le titre)
   */
  genre?: (number | null) | EventGenre;
  /**
   * Statut de publication de l'événement
   */
  status: 'published' | 'draft' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-genres".
 */
export interface EventGenre {
  id: number;
  /**
   * Nom du genre d'événement
   */
  title: string;
  /**
   * Identifiant unique du genre (utilisé dans l'URL)
   */
  slug: string;
  /**
   * Icône SVG représentant ce genre
   */
  icon?: (number | null) | Media;
  /**
   * Mots-clés utilisés pour identifier automatiquement ce genre dans les titres d'événements
   */
  keywords: {
    /**
     * Mot ou phrase à rechercher dans le titre (insensible à la casse)
     */
    keyword: string;
    id?: string | null;
  }[];
  /**
   * Description du genre (optionnel)
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  /**
   * Nom de la catégorie de menu
   */
  title: string;
  /**
   * Identifiant unique pour la catégorie
   */
  slug: string;
  /**
   * Image de la catégorie de menu
   */
  image?: (number | null) | Media;
  /**
   * Ordre d'affichage (1 = premier)
   */
  order: number;
  /**
   * Description de la catégorie (optionnel)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Statut de publication de la catégorie
   */
  status: 'published' | 'draft' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-subscribers".
 */
export interface CalendarSubscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-genres';
        value: number | EventGenre;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'calendar-subscribers';
        value: number | CalendarSubscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  time?: T;
  image?: T;
  facebookCover?: T;
  facebookLink?: T;
  genre?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-genres_select".
 */
export interface EventGenresSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  order?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-subscribers_select".
 */
export interface CalendarSubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info".
 */
export interface BusinessInfo {
  id: number;
  /**
   * Nom du café
   */
  name: string;
  /**
   * Slogan principal
   */
  tagline: string;
  /**
   * Message d'accueil
   */
  slogan: string;
  address: {
    /**
     * Adresse de rue
     */
    street: string;
    /**
     * Quartier et ville
     */
    neighborhood: string;
    /**
     * Lien Google Maps
     */
    googleMapsLink?: string | null;
  };
  social?: {
    /**
     * Lien Facebook
     */
    facebook?: string | null;
    /**
     * Lien Instagram
     */
    instagram?: string | null;
    /**
     * Lien OnlyFans (optionnel)
     */
    onlyfans?: string | null;
  };
  contact: {
    /**
     * Email général
     */
    general: string;
    /**
     * Email pour les artistes
     */
    artists?: string | null;
    /**
     * Email pour les expositions
     */
    exhibitions?: string | null;
  };
  hours: {
    lundiMercredi: {
      /**
       * Heure d'ouverture
       */
      open: string;
      /**
       * Heure de fermeture
       */
      close: string;
    };
    jeudiSamedi: {
      /**
       * Heure d'ouverture
       */
      open: string;
      /**
       * Heure de fermeture
       */
      close: string;
    };
    dimanche: {
      /**
       * Heure d'ouverture
       */
      open: string;
      /**
       * Heure de fermeture
       */
      close: string;
    };
  };
  /**
   * Message personnalisé pour les clients
   */
  message?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facebook-config".
 */
export interface FacebookConfig {
  id: number;
  /**
   * Obtenir sur: https://developers.facebook.com/tools/explorer/
   */
  accessToken: string;
  /**
   * Format: nombre (ex: 123456789012345)
   */
  pageId: string;
  /**
   * Définir quelles affiches utiliser selon les genres ou mots-clés des événements
   */
  posterRules?:
    | {
        /**
         * L'affiche qui sera automatiquement assignée
         */
        poster: number | Media;
        /**
         * Si spécifié, cette affiche sera utilisée pour tous les événements de ce genre
         */
        genre?: (number | null) | EventGenre;
        /**
         * Si spécifiés, cette affiche sera utilisée pour les événements contenant ces mots-clés dans le titre
         */
        keywords?:
          | {
              keyword: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Ordre de priorité (1 = plus haute priorité). En cas de conflit, la règle avec la priorité la plus élevée sera utilisée.
         */
        priority?: number | null;
        id?: string | null;
      }[]
    | null;
  lastImport?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-config".
 */
export interface SystemConfig {
  id: number;
  lastSeed?: string | null;
  /**
   * Informations sur le contenu du CMS
   */
  stats?: {
    totalEvents?: number | null;
    totalGenres?: number | null;
    totalMedia?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info_select".
 */
export interface BusinessInfoSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  slogan?: T;
  address?:
    | T
    | {
        street?: T;
        neighborhood?: T;
        googleMapsLink?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        onlyfans?: T;
      };
  contact?:
    | T
    | {
        general?: T;
        artists?: T;
        exhibitions?: T;
      };
  hours?:
    | T
    | {
        lundiMercredi?:
          | T
          | {
              open?: T;
              close?: T;
            };
        jeudiSamedi?:
          | T
          | {
              open?: T;
              close?: T;
            };
        dimanche?:
          | T
          | {
              open?: T;
              close?: T;
            };
      };
  message?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facebook-config_select".
 */
export interface FacebookConfigSelect<T extends boolean = true> {
  accessToken?: T;
  pageId?: T;
  posterRules?:
    | T
    | {
        poster?: T;
        genre?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        priority?: T;
        id?: T;
      };
  lastImport?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-config_select".
 */
export interface SystemConfigSelect<T extends boolean = true> {
  lastSeed?: T;
  stats?:
    | T
    | {
        totalEvents?: T;
        totalGenres?: T;
        totalMedia?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}